---

# file: learninglocker.yml

- name: Install and configure LearningLocker
  hosts: learninglocker
  roles:
    - apache
    - learninglocker
  vars_files:
    - vars.secret.yml
  tags:
    - learninglocker
    - apache
