---

- name: Set proxies as environment variables
  lineinfile:
    dest: '{{ item[0] }}'
    regexp: 'export {{ item[1].var_name }}'
    line: 'export {{ item[1].var_name }}={{ item[1].proxy_value }}'
    state: present
    backup: yes
  become: True  # for /root/.bashrc
  when: item[1].proxy_value
  with_nested:
    - ['.bashrc', '/root/.bashrc']
    - [ { var_name: 'http_proxy', proxy_value: '{{ proxy_env.http_proxy }}' },
        { var_name: 'https_proxy', proxy_value: '{{ proxy_env.https_proxy }}' },
        { var_name: 'ftp_proxy', proxy_value: '{{ proxy_env.ftp_proxy }}' } ]
  tags:
    - configure
    - proxy
    - environment


- name: Unset proxies as environment variables
  lineinfile:
    dest: '{{ item[0] }}'
    regexp: 'export {{ item[1].var_name }}'
    state: absent
    backup: yes
  when: not item[1].proxy_value
  with_nested:
    - ['.bashrc', '/root/.bashrc']
    - [ { var_name: 'http_proxy', proxy_value: '{{ proxy_env.http_proxy }}' },
        { var_name: 'https_proxy', proxy_value: '{{ proxy_env.https_proxy }}' },
        { var_name: 'ftp_proxy', proxy_value: '{{ proxy_env.ftp_proxy }}' } ]
  tags:
    - configure
    - proxy
    - environment
