---

- name: Install Git
  yum: name=git state=present
  tags:
   - install
   - git


- name: Install NodeJs and Node Package Manager (NPM)
  yum: name="{{ item }}" state=present
  with_items:
    - nodejs
    - npm
  tags:
   - install
   - nodejs
   - npm


- name: Install Bower
  npm: name=bower global=yes
  tags:
   - install
   - bower


- name: Install DeltaRPM
  yum: name=deltarpm state=present
  tags:
   - install
   - deltarpm


- name: Download Composer
  shell: "curl -sS https://getcomposer.org/installer | php"
  tags:
   - download
   - composer
   - global


- name: Install Composer and set global launch
  shell: 'mv {{ ansible_env.HOME }}/composer.phar /usr/local/bin/composer'
  tags:
   - install
   - composer
   - global


- name: Make composer executable by the user
  file:
    path: /usr/local/bin/composer
    state: file
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: ug+x
  tags:
   - permissions
   - composer
   - global
